# Generated by Django 5.1 on 2024-08-31 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sporify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musician',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
