# Generated by Django 5.1 on 2024-08-31 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sporify', '0003_alter_song_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
