# Generated by Django 5.1 on 2024-08-31 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sporify', '0007_remove_musician_user_musician_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='longetivity',
            field=models.CharField(max_length=8),
        ),
    ]
